### ISSUE TITLE
WINE: JIT DEBUGGING ERROR (ACUMATICA REPORT DESIGNER EXE)

### ISSUE THREAD

**Issue by vianggg** [kwsch/NHSE#542]
Hi, can anyone help me fix my problem with running the Acumatica Designer Report on Wine.
I already updated to the current version of wine, I also run .net ddls in winetricks. 

Here's the error i get when opening a report from a server. (Please please help)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: BelongsTo is not a valid value for FilterCondition. ---> System.FormatException: BelongsTo is not a valid value for FilterCondition. ---> System.ArgumentException: Requested value 'BelongsTo' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.EnumConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.TypeConverter.ConvertFromInvariantString(String text)
   at PX.Reports.XmlHelper.ReadValue(XmlReader reader, Object obj, PropertyDescriptor prop, TypeConverter conv)
   at PX.Reports.XmlHelper.ReadValue(XmlReader reader, Object obj, PropertyDescriptor prop)
   at PX.Reports.XmlHelper.ReadObject(XmlReader reader, Object obj)
   at PX.Reports.XmlHelper.ReadObject(XmlReader reader, Object obj)
   at PX.Reports.Controls.ReportItem.System.Xml.Serialization.IXmlSerializable.ReadXml(XmlReader reader)
   at PX.Reports.Design.ReportDesignerLoader.ReadReport(IDesignerSerializationManager manager, Report report, XmlDocument doc)
   at PX.Reports.Design.ReportDesignerLoader.ReadReport(IDesignerSerializationManager manager)
   at PX.Reports.Design.ReportDesignerLoader.PerformLoad(IDesignerSerializationManager manager)
   at System.ComponentModel.Design.Serialization.BasicDesignerLoader.BeginLoad(IDesignerLoaderHost host)
   --- End of inner exception stack trace ---
   at System.ComponentModel.Design.DesignSurface.get_View()
   at PX.Reports.Design.PXReportDesigner.LoadSurface()
   at PX.Reports.Design.PXReportDesigner.Load(String serviceUrl, String reportCode, Nullable`1 version)
   at PX.Reports.Design.PXReportDesigner.LoadFromServer(String serviceUrl, String reportCode, String user, Nullable`1 version)
   at PX.Reports.Design.PXReportDesigner.Load(String fileName)
   at ReportDesigner.MainForm.ExecuteCommand(String key)
   at System.Windows.Forms.ToolStrip.OnItemClicked(ToolStripItemClickedEventArgs e)
   at System.Windows.Forms.ToolStrip.HandleItemClick(ToolStripItem dismissingItem)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ReportDesigner
    Assembly Version: 1.0.0.0
    Win32 Version: 17.218.0015
    CodeBase: file:///C:/Program%20Files%20(x86)/Acumatica%20Report%20Designer/Report%20Designer/ReportDesigner.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Autofac
    Assembly Version: 4.3.0.0
    Win32 Version: 4.3.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Acumatica%20Report%20Designer/Report%20Designer/Autofac.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Autofac.Extras.CommonServiceLocator
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.219
    CodeBase: file:///C:/Program%20Files%20(x86)/Acumatica%20Report%20Designer/Report%20Designer/Autofac.Extras.CommonServiceLocator.DLL
----------------------------------------
Microsoft.Practices.ServiceLocation
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Acumatica%20Report%20Designer/Report%20Designer/Microsoft.Practices.ServiceLocation.DLL
----------------------------------------
PX.Reports
    Assembly Version: 1.0.0.0
    Win32 Version: 17.218.0015
    CodeBase: file:///C:/Program%20Files%20(x86)/Acumatica%20Report%20Designer/Report%20Designer/PX.Reports.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
PX.Reports.Design
    Assembly Version: 1.0.0.0
    Win32 Version: 17.218.0015
    CodeBase: file:///C:/Program%20Files%20(x86)/Acumatica%20Report%20Designer/Report%20Designer/PX.Reports.Design.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Drawing.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.Design.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
PX.Common
    Assembly Version: 1.0.0.0
    Win32 Version: 17.218.0015
    CodeBase: file:///C:/Program%20Files%20(x86)/Acumatica%20Report%20Designer/Report%20Designer/PX.Common.DLL
----------------------------------------
System.Web.DataVisualization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.DataVisualization/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.DataVisualization.dll
----------------------------------------
ReportDesigner.resources
    Assembly Version: 1.0.0.0
    Win32 Version: 17.218.0015
    CodeBase: file:///C:/Program%20Files%20(x86)/Acumatica%20Report%20Designer/Report%20Designer/en/ReportDesigner.resources.DLL
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
System.Web.Services
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by berichan** [comment]
I am closing this as stale along with a bunch of other Wine-related issues. I'm not exactly sure this is in the right place, this program is unrelated to Acumatica Designer Report.
